# Site
repository: sproogen/modern-resume-theme
favicon: images/profile.jpg

#(options: true, false, never)
darkmode: true

# Personal info
name: Yoon
title: Software Engineer
email: yoondev93@gmail.com
phone:
website:

# Social links
twitter_username:
github_username:  yoon-developer
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username:
xing_username:
pinterest_username:
youtube_username:
googleplus_username:
orcid_username:

# Additional icon links
#additional_links:
#  - title: Test link
#    icon: fab fa-ello
#    url: sproogen.github.io/modern-resume-theme
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  생년월일: 930612

  사는 곳: 서울

  사용 기술 : <mark>Java</mark> <mark>Spring-Boot</mark> <mark>JPA</mark> <mark>Linux</mark> <mark>Jenkins</mark>
  <mark>Git</mark>


# More Section
#more_title: A Little More About Me #(Use this to override about more section title)
#more_content: > # this means to ignore newlines until the next config item.
#  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests. Or you could title it **Skills**
#  and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

livereload: true


exclude:
  - vendor

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
